### ISSUE TITLE
Undefined function or variable 'environmentVariables'.

### ISSUE THREAD

**Issue by akshaykgupta** [ChunyuanLI/pSGLD#1]
Hi,

I was trying to run test_FNN_mnist.m but I got the following error:
" Undefined function or variable 'environmentVariables'. "
Can you tell me to fix it?

Thanks

**Comment by ChunyuanLI** [comment]
Hi Akshay,

Thanks for your message, I just added "environmentVariables.m", which aims to adding the directory path for matconvnet. Hope it will help.

**Comment by akshaykgupta** [comment]
Ah, it was for matconvnet.
Thanks, that fixed it!
